import Head from "next/head";
import UserCreate from "./UserCreate";


export default function Home() {
  return (
    <>
      <Head>
        <title>Registro de Usuário</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form>
          <UserCreate />
        </form>
      </main>
    </>
  );
}
